config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/post/hashtag/:name' => 'posts#hashtag'
  get    '/post/hashtag'       => 'posts#hashtag'
  get    '/signup',            to: 'users#new'
  get    '/login',             to: 'sessions#new'
  post   '/login',             to: 'sessions#create'
  delete '/logout',            to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,               only: [:new, :create, :destroy, :show] do
    resources :likes,             only: [:create, :destroy]
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :notifications,       only: [:index, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :hashtag_posts, dependent: :destroy
  has_many :hashtags, through: :hashtag_posts
  has_many :notifications, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :caption, length: { maximum: 140 }
  validates :user_id, presence: true
  validates :image, content_type: { in: %w[image/jpeg image/jpg image/png],
                                      message: "有効な画像形式である必要があります" },
                      size:         { less_than: 5.megabytes,
                                      message: "5MB未満である必要があります" }
                                      
  # フィード用のリサイズ済み画像を返す
  def display_image
    image.variant(resize_to_limit: [1000, 1000])
  end
  
  #プロフィールページ用のリサイズ済み画像を返す
  def image_gallery
    image.variant(resize_to_limit: [600, 600])
  end
  
  #投稿詳細ページ用のリサイズ済み画像を返す
  def show_image
    image.variant(resize_to_limit: [700, 700])
  end
  
  #ハッシュタグ
  def hashtag_image
    image.variant(resize_to_limit: [800, 800])
  end
  
  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end
  
  def image_presence
    if image.attached?
      if !image.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end
  
  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ",
                                  current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      
      if notification.visitor_id == notification.visited_id
         notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    #同じ投稿にコメントしているユーザーに通知を送る。（current_userと投稿ユーザーのぞく）
    temp_ids = Comment.where(post_id: id).where.not("user_id=? or user_id=?", current_user.id,user_id).select(:user_id).distinct
    #取得したユーザー達へ通知を作成。（user_idのみ繰り返し取得）
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    #投稿者へ通知を作成
    save_notification_comment!(current_user, comment_id, user_id)
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
  
  after_create do
    post = Post.find_by(id: id)
    # hashbodyに打ち込まれたハッシュタグを検出
    if post.hashbody?
      hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.uniq.map do |hashtag|
        # ハッシュタグは先頭の#を外した上で保存
        tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
        post.hashtags << tag
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :set_post, only: [:show, :destroy]
  
  def new
    @post = current_user.posts.build
  end
  
  def show
  end
  
  def hashtag
    @user = current_user
    if params[:name].nil?
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.posts.count}
    else
      @hashtag = Hashtag.find_by(hashname: params[:name])
      @post = @hashtag.posts.reverse_order
      @hashtags = Hashtag.all.to_a.group_by{ |hashtag| hashtag.posts.count}
    end
  end
  
  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "投稿に成功しました"
      redirect_to root_url
    else
      @feed_items = current_user.feed
      render 'static_pages/home'
    end
  end

  def destroy
    if @post.user == current_user
      flash[:success] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end
  
  private

    def post_params
      params.require(:post).permit(:caption, :hashbody, :image, hashtag_ids: [])
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <div class="post-wrap">
    <div class="card-header">
      <%= link_to user_path(post.user) do %>
        <div class="post-profile-icon">
         <%= gravatar_for post.user, size: 35 %>
        </div>
      <% end %>
      <%= link_to user_path(post.user), class: "black-color no-text-decoration",
        title: post.user.name do %>
        <strong class="post-user-name"><%= post.user.name %></strong>
      <% end %>
      <% if post.user_id == current_user.id %>
        <%= link_to post_path(post), method: :delete, class: "post-delete" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>
    
    <div class="post-image">
      <%= link_to(post_path(post)) do %>
        <%= image_tag post.display_image if post.image.attached? %>
      <% end %>
    </div>
    
    <div class="card-body">
      <div class="card-top">
        <div id="like-icon-post-<%= post.id.to_s %>">
          <% if post.liked_by(current_user).present? %>
            <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :delete, remote: true, class: "loved hide-text" %>
          <% else %>
            <%= link_to "いいね", post_likes_path(post), method: :post, remote: true, class: "love hide-text" %>
          <% end %>
        </div>
        <%= link_to post_path(post) do %>
        <div class="comment"></div>
        <% end %>
      </div>
      <div id="like-text-post-<%= post.id.to_s %>">
        <%= render "posts/like_text", { likes: post.likes } %>
      </div>
      
      <div>
        <span><strong><%= post.user.name %></strong></span>
        <span><%= post.caption %></span>
        <br>
        <span><%= link_to post.hashbody, post_path(post) if post.hashbody? %></span>
        <br>
        <span class="timestamp">
          <%= time_ago_in_words(post.created_at).upcase + "前" %>
        </span>
        <div id="comment-post-<%= post.id.to_s %>">
          <%= render 'posts/comment_list', { post: post } %>
        </div>
        <hr>
        <div class="comment-width" id="comment-form-post-<%= post.id.to_s %>">
          <%= form_with model: [post, Comment.new] do |f| %>
            <div class="input-group">
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: post.id %>
              <%= f.text_field :comment, class: "form-control", placeholder: "コメント ...", autocomplete: :off %>
              <span class="input-group-btn">
                <%= f.submit "投稿", class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/posts/hashtag.html.erb
<% provide(:title, "ハッシュタグ") %>
<div class="hashtag-post-wrap">
  <% if params[:name] == nil %>
  <% else %>
    <h3 class="search-title">#<%= @hashtag.hashname %>:  <%= @post.count %> 件 </h3>
    <div class="row">
      <% @post.each do |post| %>
        <div class="col-md-6">
          <div class= "hashtag-post-box">
            <%= link_to post_path(post) do %>
              <div class="hashtag-post-header">
                <%= link_to user_path(post.user) do %>
                  <div class="hashtag-profile-icon">
                   <%= gravatar_for post.user, size: 40 %>
                  </div>
                <% end %>
                <%= link_to user_path(post.user), class: "black-color",
                        title: post.user.name do %>
                  <strong class="hashtag-user-name"><%= post.user.name %></strong>
                <% end %>
              </div>
              <div class="hashtag-post-image">
                <%= link_to(post_path(post)) do %>
                  <%= image_tag post.hashtag_image if post.image.attached? %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %> 
  <hr class="hashtag-hr">
  <div class="row">
    <div class= "col-xs-12 col-lg-12 col-md-12 col-sm-12">
      <div class= "hashtag-name">
        <% @hashtags.sort.reverse.each do |count| %>
          <% count[1].each do |hashtag| %>
            <p class="hashtag-name-margin">
              <%= link_to "##{hashtag.hashname} (#{hashtag.posts.count})","/post/hashtag/#{hashtag.hashname}" %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, '投稿する') %>
  <div class="form-box">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="gravatar_edit">
          <%= link_to gravatar_for(current_user, size: 50), current_user %>
        </div>
        <section>
          <%= form_with model: @post, local: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <%= f.text_area :caption, class: "form-control", placeholder: "キャプションを書く" %>
            
            <%= f.text_field :hashbody, class: "form-control", placeholder: "ハッシュタグを書く" %>
            
            <%= f.submit "投稿", class: "btn btn-primary" %>
            
            <span class="image">
              <%= f.file_field :image, accept: "image/jpeg,image/jpg,image/png" %>
            </span>
          <% end %>
        </section>
      </div>
    </div>
  </div>
  
  <script type="text/javascript">
  $("#post_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("最大ファイルサイズは5MBです。小さいファイルを選択してください。");
      $("#post_image").val("");
    }
  });
</script>

app/views/posts/show.html.erb
<% provide(:title, "投稿の詳細") %>
<div class="row post-show-wrap post-show-frame">
  <div class="col-md-8">
    <div class="card-left">
      <%= image_tag @post.show_image if @post.image.attached? %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card-right">
      <div class="card-right-comment">
        <div class="card-right-header">
          <div class="post-show-icon">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= gravatar_for @post.user, size: 35 %>
            <% end %>
          </div>
          
          <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-show-name",
            title: @post.user.name do %>
            <strong><%= @post.user.name %></strong>
          <% end %>
          
          <% if @post.user_id == current_user.id %>
            <%= link_to post_path(@post), method: :delete, class: "post-show-delete" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
        <div class="post-contents">
          <strong>
            <%= @post.caption %>
            <br>
            <%= render_with_hashtags(@post.hashbody) %>
          </strong>
        </div>
        <div id="comment-post-<%= @post.id.to_s %>">
          <%= render 'comment_list', post: @post %>
        </div>
      </div>
      <div class="action-parts">
        <div class="parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :delete, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :post, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", { likes: @post.likes } %>
        </div>
        <div class="timestamp"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr class="post-show-hr">
        <div id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_with model: [@post, Comment.new] do |f| %>
            <div class="input-group">
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: @post.id %>
              <%= f.text_field :comment, class: "form-control", placeholder: "コメント ...", autocomplete: :off %>
              <span class="input-group-btn">
                <%= f.submit "投稿", class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>