config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/post/hashtag/:name' => 'posts#hashtag'
  get    '/post/hashtag'       => 'posts#hashtag'
  get    '/signup',            to: 'users#new'
  get    '/login',             to: 'sessions#new'
  post   '/login',             to: 'sessions#create'
  delete '/logout',            to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,               only: [:new, :create, :destroy, :show] do
    resources :likes,             only: [:create, :destroy]
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :notifications,       only: [:index, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to root_path, id: "logo" do %>
      <%= image_tag 'header-logo.jpg' %>
    <% end %>
    <nav id="global-nav">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to root_path, :method => :get do %>
            <i class="fas fa-home fa-2x"></i>
          <% end %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to new_post_path, :method => :get do %>
              <i class="fas fa-camera fa-2x"></i>
            <% end %>
          </li>
          <li>
            <%= link_to notifications_path, :method => :get do %>
              <i class="far fa-heart fa-2x"></i>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <div class="header-gravatar">
                <%= gravatar_for current_user, size: 33 %>
              </div>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "ユーザー", users_path %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to login_path, :method => :get do %>
              <i class="fas fa-sign-in-alt fa-2x"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-179982892-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      
      gtag('config', 'UA-179982892-1');
    </script>
    
    <%= favicon_link_tag 'icon-R2.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="日々の日常や体験、クリエイティブな写真を投稿して、友人や家族と共有しよう。">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>